--- 
server:
  port: ${vcap.application.port:8071}
eureka: 
  client: 
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl: 
      defaultZone: ${vcap.services.eureka.credentials.uri}/eureka
  instance: 
    hostname:  ${vcap.application.uris[0]}
    nonSecurePort: 80
spring: 
  profiles: cloud
